### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by zhanglu993** [zlgopen/awtk-stm32f429igtx-raw#1]
..\awtk\src\base\custom_props.c(77): error:  #513: a value of type "int" cannot be assigned to an entity of type "const wchar_t *"

**Comment by xianjimli** [comment]
这个问题很奇怪，我在多个平台上都没有重现。有点像wcs_dup没有声明的错误，但是wcs_dup在base/wstr.h中声明了啊。你有空的话帮我看看，谢谢

**Comment by zhanglu993** [comment]
应该是我编译环境的问题，我重新更新了整个环境已经好了，不好意思了

**Comment by xianjimli** [comment]
好的，谢谢你
