### ISSUE TITLE
在Keil上编译有61个Warnings

### ISSUE THREAD

**Issue by hk-mars** [zlgopen/awtk-stm32f429igtx-raw#7]
**[问题]**
在Keil上编译有61个Warnings

**[当前结果]**
 > "..\OBJ\awtk.axf" - 0 Error(s), 61 Warning(s).**

**[期望结果]**
修复warnings, 编译结束无warning或极少warning。

**Comment by xianjimli** [comment]
主要是第三方库stb里的警告，目前没有办法修改。
